# 로컬 개발 환경
# Run with: docker-compose -p tars up -d

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tars
      MYSQL_USER: local_user
      MYSQL_PASSWORD: local_password
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data: