spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{ secrets.RDS_URL }}
    username: ${{ secrets.RDS_ID }}
    password: ${{ secrets.RDS_PW }}

  jpa:
    hibernate:
      ddl-auto: update        # DB ??? ?? (none, create, create-drop, update, validate)
    properties:
      hibernate:
        format_sql: true
        show_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
