spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_ID}
    password: ${RDS_PW}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true     
        show_sql: true  
