name: Java CD with Gradle
 
on:
  push:
    branches: [ "dev" ] 
  pull_request:
    branches: [ "dev" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # (3) Gradlew에 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
        
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cicdsample
          path: build/libs/*.jar
 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: cicdsample
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: SCP transfer
        run: scp *.jar ${{ secrets.USER_ID }}@${{ secrets.SERVER_IP }}:~/cicd
      - name: Execute remote commands
        run: |
          ssh ${{ secrets.USER_ID }}@${{ secrets.SERVER_IP }} "sudo fuser -k 8080/tcp"
          ssh ${{ secrets.USER_ID }}@${{ secrets.SERVER_IP }} "sudo nohup java -jar ~/cicd/*.jar &"
