name: 'Submodules Sync'

on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless of whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository and submodules
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          submodules: true

      # Ensure all submodules are on the correct branch (live)
      - name: Git Submodule Update
        run: |
          git submodule update --init --recursive
          git submodule foreach --recursive 'git checkout live || true'
          git submodule foreach --recursive 'git pull origin live || true'
          git submodule foreach --recursive git reset --hard
          git submodule foreach --recursive git clean -df

      # Commit and push updates (if there are changes)
      - name: Commit and push updates
        run: |
          git diff --exit-code || {
            git config --global user.name 'Git bot'
            git config --global user.email 'bot@noreply.github.com'
            git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}
            git add .
            git commit -m "Auto updated submodule references"
            git push origin HEAD:live
          } || echo "No changes to commit"