name: 'Submodules Sync'

on:
  workflow_dispatch:

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository and submodules with token for authentication
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}  # Ensure the token is correctly passed
          submodules: true  # Submodules will be checked out

      # Ensure all submodules are on the correct branch (live)
      - name: Git Submodule Update
        run: |
          git submodule update --init --recursive
          git submodule foreach --recursive 'branch=$(git symbolic-ref --short -q HEAD); if [ "$branch" != "live" ]; then git checkout live; fi'
          git submodule foreach --recursive 'git fetch origin live && git reset --hard origin/live'
          git submodule foreach --recursive git clean -df

      # Commit and push updates (if there are changes)
      - name: Commit and push updates
        run: |
          git diff --exit-code || {
            git config --global user.name 'Git bot'
            git config --global user.email 'bot@noreply.github.com'
            git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}
            git add .
            git commit -m "Auto updated submodule references"
            git push origin HEAD:live
          } || echo "No changes to commit"